### ISSUE TITLE
Signup for new email account

### ISSUE THREAD

**Issue by nobuti** [DRD4-7R/Onboarding-antonio#1]
Ask @xavijam for an email account. Then set it up with your own settings.

### How to test it

- [x] Go to http://ismyemailworking.com/ and enter your new and shiny email address
- [x] Once you receive the first email, reply
- [x] Wait until the email confirmation arrives
- [x] Open a PR and change your base repo's readme file to include your new email addres

**Comment by tripu** [comment]
Closed accidentally because there was no `master` branch in the repo, and I messed with it until I realised of that.

**Comment by xavijam** [comment]
you have your email ready!
